name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    name: 'Lint & Tests'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Deps
        run: |
          yarn install

      - name: Lint
        run: |
          yarn run lint
